/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package alugueldeveiculos;

import control.Controlador;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Laís Isabella
 */
public class UIListagensVeiculos extends javax.swing.JDialog {
    

    /**
     * Creates new form UIListagensVeiculos
     */
    public UIListagensVeiculos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        radioTodos = new javax.swing.JRadioButton();
        radioNacionais = new javax.swing.JRadioButton();
        radioImportados = new javax.swing.JRadioButton();
        radioDisponiveis = new javax.swing.JRadioButton();
        radioLocados = new javax.swing.JRadioButton();
        radioAtrasados = new javax.swing.JRadioButton();
        radioCNH = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaListagens = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        buttonListar = new javax.swing.JButton();
        comboCNH = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Light", 1, 24)); // NOI18N
        jLabel1.setText("Listagens de veículos");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel2.setText("Selecione qual relatório você deseja listar:");

        buttonGroup.add(radioTodos);
        radioTodos.setText("Veículos Cadastrados");
        radioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosActionPerformed(evt);
            }
        });

        buttonGroup.add(radioNacionais);
        radioNacionais.setText("Veículos Nacionais");
        radioNacionais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNacionaisActionPerformed(evt);
            }
        });

        buttonGroup.add(radioImportados);
        radioImportados.setText("Veículos Importados");
        radioImportados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioImportadosActionPerformed(evt);
            }
        });

        buttonGroup.add(radioDisponiveis);
        radioDisponiveis.setText("Veículos Disponíveis");
        radioDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDisponiveisActionPerformed(evt);
            }
        });

        buttonGroup.add(radioLocados);
        radioLocados.setText("Veículos Locados");
        radioLocados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLocadosActionPerformed(evt);
            }
        });

        buttonGroup.add(radioAtrasados);
        radioAtrasados.setText("Veículos com devolução atrasada");
        radioAtrasados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAtrasadosActionPerformed(evt);
            }
        });

        buttonGroup.add(radioCNH);
        radioCNH.setText("Veículos disponíveis com CNH necessária");
        radioCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCNHActionPerformed(evt);
            }
        });

        textAreaListagens.setColumns(20);
        textAreaListagens.setRows(5);
        jScrollPane1.setViewportView(textAreaListagens);

        buttonListar.setText("LISTAR");
        buttonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListarActionPerformed(evt);
            }
        });

        comboCNH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", " " }));
        comboCNH.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioDisponiveis)
                                    .addComponent(radioImportados)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioCNH)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(radioNacionais)
                                    .addComponent(radioTodos)
                                    .addComponent(jLabel2)
                                    .addComponent(radioAtrasados)
                                    .addComponent(radioLocados)
                                    .addComponent(buttonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(radioTodos)
                        .addGap(18, 18, 18)
                        .addComponent(radioNacionais)
                        .addGap(18, 18, 18)
                        .addComponent(radioImportados)
                        .addGap(18, 18, 18)
                        .addComponent(radioDisponiveis)
                        .addGap(18, 18, 18)
                        .addComponent(radioLocados)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioCNH, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioAtrasados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(buttonListar)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioAtrasadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAtrasadosActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
    }//GEN-LAST:event_radioAtrasadosActionPerformed

    private void radioCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCNHActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
        comboCNH.setVisible(true);
       
        comboCNH.setEnabled(true);
    }//GEN-LAST:event_radioCNHActionPerformed

    private void buttonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListarActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        Controlador control = new Controlador();
        
        if(radioTodos.isSelected()){
            textAreaListagens.setText(control.ListarTodosVeiculosCadastrados());
        } else 
            if(radioNacionais.isSelected()){
                textAreaListagens.setText(control.ListarTodosVeiculosNacionais());
            } else 
                if(radioImportados.isSelected()){
                    textAreaListagens.setText(control.ListarTodosVeiculosImportados());
                } else 
                    if(radioLocados.isSelected()){
                        textAreaListagens.setText(control.ListarTodosVeiculosAlugados());
                    } else
                        if(radioDisponiveis.isSelected()){
                            textAreaListagens.setText(control.ListarTodosVeiculosDisponiveis());
                        }
                        if(radioCNH.isSelected()){
                           int index = comboCNH.getSelectedIndex();
                           String cnh = "";
                           switch(index){
                               case 0:
                                   cnh = "A";
                                   break;
                                   
                               case 1:
                                   cnh = "B";
                                   break;
                                   
                               case 2:
                                   cnh = "C";
                                   break;
                                
                               case 3:
                                   cnh = "D";
                                   break;
                                   
                               case 4:
                                   cnh = "E";
                                   break;
                           }
                           
                           textAreaListagens.setText(control.ListarVeiculosDisponiveisCNHEspecifica(cnh));
                           
                        }else 
                            if(radioAtrasados.isSelected()){
                                textAreaListagens.setText(control.ListarTodosVeiculosComAtrasoDevolucao());
                            } 
//                            else {
//                                JOptionPane.showMessageDialog(jFrame, "Selecione algum opção de listagem!");
//                            }
        
    }//GEN-LAST:event_buttonListarActionPerformed

    private void radioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
    }//GEN-LAST:event_radioTodosActionPerformed

    private void radioNacionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNacionaisActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
    }//GEN-LAST:event_radioNacionaisActionPerformed

    private void radioImportadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioImportadosActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
    }//GEN-LAST:event_radioImportadosActionPerformed

    private void radioDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDisponiveisActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
    }//GEN-LAST:event_radioDisponiveisActionPerformed

    private void radioLocadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLocadosActionPerformed
        // TODO add your handling code here:
        textAreaListagens.setText("");
    }//GEN-LAST:event_radioLocadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIListagensVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIListagensVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIListagensVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIListagensVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIListagensVeiculos dialog = new UIListagensVeiculos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                   
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonListar;
    private javax.swing.JComboBox<String> comboCNH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radioAtrasados;
    private javax.swing.JRadioButton radioCNH;
    private javax.swing.JRadioButton radioDisponiveis;
    private javax.swing.JRadioButton radioImportados;
    private javax.swing.JRadioButton radioLocados;
    private javax.swing.JRadioButton radioNacionais;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JTextArea textAreaListagens;
    // End of variables declaration//GEN-END:variables
}
